### ISSUE TITLE
Custom status code when no route found

### ISSUE THREAD

**Issue by discobean** [eBay/fabio#107]
Hi, currently fabio returns a 404 if no route is found.

We have nginx in front that routes a 404 to another fabio instance in DC2 if DC1 service is unavailable.  But this causes a problem if a microservice responses with a legitimate 404 in DC1 as the request would be routed twice by nginx.

How could this use case be supported?  I was hoping for a custom response code if no route is found, but I could not find anything in the documentation.

**Comment by magiconair** [comment]
Good point. I've added a patch which adds this feature. Let me know if this works.

**Comment by magiconair** [comment]
I'm also thinking whether this is something that fabio could do natively. It could determine the fabio instances in another data center and route requests for failed routes there. This would save another roundtrip since fabio knows which routes it has. 

Can you explain your use case a bit more and which other functions your nginx is serving?

**Comment by discobean** [comment]
We use nginx for offloading SSL, ACLs, rewrites and these sorts of more complicated tasks.

If fabio were to route to another DC then it would solve another problem we have - where if one microservice fails in DC1 all nginx routes all microservices attached to that upstream to DC2.

I'll test your patch next week and let you know.

**Comment by magiconair** [comment]
I'm going to merge this one. The change is simple enough. Please re-open if this doesn't work as intended.

**Comment by discobean** [comment]
Hi, can confirm this now works! 👍
