### ISSUE TITLE
Extended metrics

### ISSUE THREAD

**Issue by robholland** [eBay/fabio#125]
We're interested in measuring the impact of switching a system over to fabio versus a haproxy setup, it would be very useful to have a Counter() per HTTP status code so we can check for behaviour versus our current setup, ensuring the 200/202/404 rates are equivalent.

Also it would be useful to have a Counter() for route-not-found responses (proxy.noroutestatus) as they won't be associated with a route target.

**Comment by magiconair** [comment]
Sounds good. I'll see what I can do.

**Comment by magiconair** [comment]
@robholland The patch I've uploaded should do the trick. 

```
    * Add 'noroute' counter for requests to non-existing routes
    * Add 'http.status.xxx' timer for responses with a specific status code
    * Add 'ws.conn' counter for counting number of open websockets
```

I'm a bit torn by keeping track of all status codes since this code is in the hot path. The generic implementation has to create the metric name and lookup the timer for every request which means 1-2 allocs and accessing a (global?) lock. 

A possible optimization would be to limit the number of status codes fabio keeps track of and make that configurable. Then I can pre-alloc the timers and don't have to look them up. 

If it is easy for you to run a load test to see whether that makes a difference then that would help a lot. I'll see what I can do on our end. For now, I've opted for the more useful implementation but I'll merge this after I've seen some numbers.

**Comment by robholland** [comment]
Frank, we're going to have to halt our fabio experiments as our priorities have changed. If you're keen on getting this merged and need some testing then I'll try and make some time for it in a few weeks.

Thanks for your efforts getting us this far, hopefully we'll be back :)

**Comment by magiconair** [comment]
@robholland No problem. I think this one has enough value. I'll run this in our environment first to see how it behaves. Let me know if/when I can help again.

**Comment by magiconair** [comment]
Rebased this on top of #147

**Comment by maier** [comment]
```go
type cgmCounter struct {
	metrics *cgm.CirconusMetrics
	name    string
}

func (m *cgmRegistry) GetCounter(name string) Counter {
	metricName := fmt.Sprintf("%s`%s", m.prefix, name)
	return &cgmCounter{m.metrics, metricName}
}

func (c cgmCounter) Inc(n int64) {
	c.metrics.IncrementByValue(c.name, uint64(n))
}
```

**Comment by magiconair** [comment]
Merged to master.
