### ISSUE TITLE
consul.addr rename

### ISSUE THREAD

**Issue by aldarund** [eBay/fabio#132]
Its not good to change option without backward compatability.
We are using docker image of fabio
and suddenly our site stopped working after update.
Traced the problem down to fabio, and it appeared that we were using consul.addr which was fine before, and now its renamed to registry.consul.addr.

**Comment by magiconair** [comment]
@aldarund I am sorry to hear that. 

`consul.addr` has been deprecated and replaced by `registry.consul.addr` in commit [5250bac](https://github.com/eBay/fabio/commit/5250bacfc46d0d47b935256bdde425af480d47dc#diff-f1ea9ed43b0b0ed74a6cf0f71dad3196) in adding support for issue #12 - multiple backends and went live with release 1.1 on 18 Feb 2016. Since then your log should have contained the following output:

```
$ ./fabio -cfg fabio.properties
2016/07/24 20:16:38 [INFO] Version 1.1 starting
2016/07/24 20:16:38 [WARN] config: consul.addr has been replaced by registry.consul.addr
2016/07/24 20:16:38 [INFO] Runtime config
...
```

Over the last five months I've released 6 more releases (1.1.1 - 1.1.6) and four RCs for 1.2 which all contained the same warning. 

Also, https://hub.docker.com/r/magiconair/fabio/tags/ lists all fabio versions up to 1.0.2 including the latest RCs for 1.2 in addition to `latest`. You can refer to a specific version as follows:

```
docker pull magiconair/fabio:<version>

e.g.

docker pull magiconair/fabio:1.1.6-go1.6.2
```

Using `latest` has some risks since you assume that nothing will break or change between versions. 

I do my best not to break things for one to prevent situations like yours since that clearly does not make people happy. But also because we are using fabio in our production environment. Bringing down a site like marktplaats.nl because of an upgrade that contains an edge case I've overlooked would be too dangerous. That's why we pin our versions per environment and roll out newer versions in our test environments and on our laptops first. 

Since most of the development work is currently shouldered by me, I'm human and make mistakes I don't feel that I'm in the position to give a lifetime backwards compatibility guarantee like the Go team for Go 1 for example since that would prevent me from removing anything that has become obsolete over time. Some design decisions I made turned out to be too narrowly focussed. They made sense at the time but don't fit when requirements changed. I want to be able to change things. 

Also, I don't control packaging or how and when people roll-out fabio in their environment. I don't control how they stay informed, whether they check the CHANGELOG or Twitter.

Combine this with wanting to change things means that I can only depend on fabio users following best practices and a defensive approach when using fabio in their own environment. 

I think your approach of running `latest` on your production site without testing it first is a bit reckless. With this you're destined to get burned at some point.

However, I should have probably mentioned the removal in the CHANGELOG and announced it beforehand instead of just dropping it after a couple of months; although, I'm not sure if that would have helped in your case. 

I'm open for suggestions on how to handle deprecations of features, config options and behavior in the future.

**Comment by magiconair** [comment]
At the time I've decided to rely on log messages only for deprecation warnings. Maybe fabio is too stable or doesn't get restarted often enough for people to notice.

**Comment by magiconair** [comment]
I am going to close this one but feel free to comment for further suggestions.
