### ISSUE TITLE
Vault token should not require 'root' or 'sudo' privileges

### ISSUE THREAD

**Issue by far-blue** [eBay/fabio#134]
I'm investigating the new integration options for fabio with cert stores, esp. vault (btw. great work, really looking forward to using it!) and I'm struggling with Vault Tokens.

I've created an orphan token with a limited policy but when I try to use it with Fabio I'm getting the following:

> 2016/07/26 12:35:57 [FATAL] vault: client: Error making API request.
> 
> URL: POST http://vault-server:8200/v1/auth/token/create
> Code: 400. Errors:
> 
> * root or sudo privileges required to create orphan token

This would suggest Fabio needs a token with a root policy. I'm not sure I'm happy about having a token with root-level access floating about my config files and live environments.

Is there a reason fabio needs a root token? Am I doing something wrong?

**Comment by magiconair** [comment]
I'll have a look.

**Comment by magiconair** [comment]
I don't think this is a hard requirement. I've created the fabio token as an orphaned token which apparently requires these privileges. I'll check what the best approach is and make this configurable if necessary. If you have suggestions on how to set this up feel free to comment.

**Comment by far-blue** [comment]
Maybe it would help to understand why you are trying to create an orphan token?

My assumption was that I would be responsible for supplying a token and keeping it renewed and all Fabio would do was use the token it was given. If you prefer to generate short-lived tokens based on the supplied token on startup and then cycle them internally for your own reasons then I think that will still work. 

Orphaning the token would mean it wasn't revoked when the parent token was revoked which is probably not the behaviour you want - and, of course, orphaning can only be done by root.

In fact, the token I'm supplying is itself orphaned as I didn't want it related to my login token but I think that's something for the Vault admin to deal with rather than Fabio :)

**Comment by magiconair** [comment]
The rationale is that you provide a short-lived (e.g. 30s) token to fabio during startup so that fabio could generate its own token which it continues to use and extend as long as it is running. Otherwise, anybody who can inspect the environment via the `/proc` filesystem or the command line arguments would be able to re-use the token. 

However, it is perfectly possible that I misunderstood something and that this is achievable without creating an orphan token. I remember having a discussion on the Vault approach fabio takes with @jeffrai - the Vault maintainer. I'll dig into the docs again.

**Comment by far-blue** [comment]
To combat the problem of the token being visible you could make use of the new 'wrapping' capability in Vault. With this facility, the token supplied to Fabio would be a one-use token and fabio would query Vault using the `unwrap` endpoint to fetch the actual token to use. Other than this extra step the token will behave as normal.

The problem with this approach is that a new wrapped token would be needed every time Fabio is started meaning some form of automated script would prob. be needed to do it and that script would then need its own token in order to generate the wrapped token. I guess the advantage here is that this script would be short-lived and while you'd need to protect the token on disk you'd not see it in memory. After all, we are used to storing private cert keys on disk and if the token was stolen then it would only give access to the same private certs that could have been stolen from disk with the same level of access as the token - and the token can at least be revoked easily!

The other problem is one of renewing the token because this is another task prob. best automated and so, again, another script needing a token.

I'd be interested in what @jeffrai suggests :)

**Comment by magiconair** [comment]
I think I prefer the approach where fabio gets the ability to create and manage its own token since you then don't have to worry about renewals and visibility. In your approach you'd still need a short-lived token to bootstrap fabio only for fabio to re-use the same token and move token renewal outside of fabio. 

One question is whether that requires the creation of an orphaned token. Another is what happens when the parent token expires? This should invalidate the child tokens as well. And I also need to check whether I deal with the expired token the right way, i.e. invalidate the cert store instead of treating it as "connection error" which means that the certs remain valid. 

In our environment we don't restart fabio for days, weeks or even months. It just runs and we forget about it. 

As far as I recall the conversation with @jeffrai during HashiConf EU he suggested the approach of the short-lived startup token. But at that time Vault 0.6.0 was just out and the guy was quite popular. Not sure if we had enough time to talk about it in-depth.

**Comment by magiconair** [comment]
Hmm, this won't work. If you pass a short-lived token to fabio and create a renewable child token with it then the child will expire when the parent expires unless I'm missing something. 

I've used this ACL:

```
path "secret/fabio/*" {
  capabilities = ["read"]
}

// do we need this?
path "auth/token/lookup-self" {
  capabilities = ["read"]
}

path "auth/token/create" {
  capabilities = ["create", "update"]
}

path "auth/token/revoke" {
  capabilities = ["delete"]
}
```

**Comment by far-blue** [comment]
I don't think fabio needs to create child tokens and I don't think it should create orphan tokens. Fabio's token is basically a password or an oauth type key and so it would make sense for an external system to create a token with specific permissions (i.e. policy) and hand it to fabio to use.

Firstly, it makes sense for the token to expire if not used. But it looks like there is support for self-renewal of a token (assuming the token, when created, was set to allow renewal and the policy is configured to allow it as well).  See the '/auth/token/renew-self' POST endpoint in the docs (link at the end of the comment). I'm not sure how you can find out the expiration of the token given to fabio but when you renew-self you get back info on the lease duration which you could log in consul so as to renew again in good time (and rinse/repeat).

I don't think it's a good idea to create orphan child tokens because whoever / whatever gave the token to fabio should retain the ability to revoke access. If orphan child tokens are created the revocation process is significantly harder or possibly even impossible.

To cover your concerns about the token being provided to fabio in a way that is sniffable, I suggest support for wrapped tokens. The token provided to fabio on startup would be a one-shot wrapped token which fabio would use to fetch the actual token. Pretty much anything in Vault starting v0.6 can be wrapped and this functionality makes use of the cubbyhole secret backend. 

A final and somewhat different approach would be to skip the tokens entirely and use the AppID auth backend to authenticate. Here, you could accept the appId via an env var and calculate the userId through some machine-specific value (mac address is suggested but not sure that's sensible in a container). You can also lock the appId/userId combinations down to a certain CIDR. Authentication is linked to a policy and so you still end up with a token with ACLs which you can, I assume, renew as needed as long as fabio is running. Arguably, however, this authentication could be the job of a pre-launch helper script which does the login and fetches a wrapped token which is then supplied to fabio as in the previous paragraph.

https://www.vaultproject.io/docs/auth/token.html
https://www.vaultproject.io/docs/secrets/cubbyhole/index.html
https://www.vaultproject.io/docs/auth/app-id.html

**Comment by far-blue** [comment]
Thinking about it, maybe @jeffrai was referring to these 'wrapped' tokens when he talked about the short-lived startup tokens.

**Comment by magiconair** [comment]
Possibly. OK, then fabio would get a token, unwrap it and renew it on a regular basis. I think that makes sense.

**Comment by magiconair** [comment]
I think I have something working but this needs a bit more refactoring since the current code tries to unwrap the token twice which won't work.

**Comment by magiconair** [comment]
@far-blue I've pushed a patch that changes the way fabio integrates with vault. It will use the provided token instead of creating a new one and will transparently unwrap a wrapped token. fabio still tries to refresh the token on every refresh cycle but it will no longer fail if it can't. However, it logs a warning on every failure which has the potential of filling up the logs quickly if provided with a non-renewable token. I've also updated the integration test to use a policy to limit the required capabilities. 

I think this is starting to look better than the original approach but I need to test the edge cases a bit more. It would be great if you could test this setup.

The required policies are (assuming that you configured your cert store with `secret/fabio/cert`):

```
  path "secret/fabio/cert" {
    capabilities = ["list"]
  }

  path "secret/fabio/cert/*" {
    capabilities = ["read"]
  }
```

**Comment by far-blue** [comment]
That's great. I'm on holiday for a couple of days but I'll try and test the patch out and let you know :)

I assume if Fabio tries to refresh the token it will need permissions to do this so does the policy also need to include `auth/token/renew-self` and possibly `auth/token/lookup-self`?

**Comment by magiconair** [comment]
I would have assumed that as well but the test registers this policy and refreshes the token on every cert refresh cycle. Since that didn't cause an error maybe that is included in the `default` policy. Enjoy your holiday :)

**Comment by magiconair** [comment]
@far-blue any chance looking at this?

**Comment by far-blue** [comment]
Hello :) Yes, been catching up on work after holiday but have had a chance this morning to test things. The log doesn't mention much about vault and tokens but I can confirm that when I provide a non-root token with the policy you mentioned above then fabio does indeed start for me without error and can access the specified vault path. Changing the path in the config causes an error and fabio will quit - so the policy is working and the token is working.

The one thing I'm still not sure about is when and whether the token will renew. I'm not sure what the `"Refresh": 3000000000,` means in the vault section of the config output on startup - is it 30 seconds, 5 mins, 34 days etc. I've tried querying the token via vault but either Fabio is renewing the token expiry every few seconds or querying the token with vault changes its last-renewal time because every time I query I get effectively the current date/time.

I'll keep experimenting and I'm yet to see any log output suggesting fabio tried and failed to renew the token - but I've also yet to see any log output suggesting fabio tried and succeeded either. Some additional log output might be quite useful to confirm to users on startup that accessing Vault was successful and when tokens have renewed.

I've yet to test and confirm wrapped tokens so I'll try that next.

**Comment by far-blue** [comment]
Ok, I can confirm unwrapping and I can confirm correct termination of fabio if the unwrapping token itself has expired or already been accessed.

**Comment by magiconair** [comment]
That's good news. I'll add some more logging to the code. The only concern is to flood the logs but I'll check what can be done about that. The `Refresh` values are a `time.Duration` which means they are in `ns`. Default is `3s`. Might be a good idea to or render them as string.

**Comment by far-blue** [comment]
I think really 3s is a little too often for my needs. The default expiry for a vault token is 1 hour although you can set it when you create the token. It might be good to fetch the token TTL when fabio first starts (as I assume it will refresh the token as soon as it starts anyhow) and then set the refresh period to something related to the TTL - such as 75%. That way the creator of the token can control the renewal rate.

**Comment by far-blue** [comment]
I've left fabio running far longer than the TTL on the token I gave it and it has not complained so I assume it is correctly refreshing the token. However, as I've not got much fabio might be fetching from vault at the moment I don't know whether it might fail to fetch if it tried. Overall, looks good to me :)

**Comment by far-blue** [comment]
Regarding the refresh, are you supplying a renewal increment? Because it looks like although you are refreshing every few seconds the lease is actually being renewed for an hour (the default lease length in Vault). Again, this could be based on the creation TTL from the token info instead.

**Comment by magiconair** [comment]
The refresh interval and token extension interval solve different problems:

The refresh interval is the time it takes fabio to detect a certificate for a domain it did not have before. It also determines how quickly fabio will act upon a deleted certificate or a revoked token.

The token extension interval protects (or is supposed to protect) fabio from intermittent failures of vault. fabio could fetch new certs lazily but at this moment I'm concerned about thundering herd issues during startup. Also, I don't want fabio to shut down because it cannot reach vault.

I think the latter part could use some more thought since both the cert and the token have a TTL which fabio could honor. But even then you'd want fabio to honor a revoke operation quickly. 

Regarding refresh: as long as vault does not offer a way to notify a watcher for changes (like consul) then I don't see an alternative to constant polling. Configuring certificates in an external store becomes interesting if you have too many or if they change too often to configure them manually. But then you want fabio to react as soon as the cert is there/gone just like with the services.

**Comment by far-blue** [comment]
I can see your concerns regarding the time it takes to pick up a new certificate for a domain and your concerns about stampeding. My gut reaction to such a problem would be to do an initial fetch of all certs during startup and then an on-demand fetch for certs for domains where no cert currently exists in order to pick up new ones. You could combine this with a longer periodic refetch to handle updates and revocations and I believe there is already support for signals for force-reloading the config in case of emergency. 

You are correct in saying Vault doesn't have events and watch capabilities but I think rapid polling is not really appropriate and maybe something 'out-of-band' using a better trigger such as a consul gossip event, kv change or os signal would be worth considering. I think I'll also suggest to the Vault developers the option to configure consul events on actions on definable paths. Technically they already have the framework because they have audit backends.

Whatever option(s) you choose for checking and refreshing certs, I don't think the vault auth token needs to be renewed every few seconds. I think it needs decoupling from any fetching of data from vault and run on a longer period - possibly, as I suggest, based on a percentage of the TTL of the token when it was created. You don't need to renew the token on every use.

**Comment by far-blue** [comment]
fyi: https://github.com/hashicorp/vault/issues/1712

**Comment by magiconair** [comment]
yes, I agree. That would be a saner implementation. The question is whether the added complexity will have any benefits. The current implementation is straightforward, simple and robust. Since it always fetches everything there is no doubt on what the current state is. Since it always refreshes the token I don't have to have another timer for this. 

Also, I don't consider polling every 3s rapid. Even with 10 concurrent fabio instances you're only generating 30 req/sec which should be cheap and come from memory (but may not now that I think about it since you may be using an external storage like S3). We're easily handling 1000 req/sec on a single service for a cached response with < 1ms latency and not a lot of CPU load. 

Preferably, I'd like to have the lazy fetching implemented at a higher level so that this doesn't become something vault specific. I'll think about this and check on how to refactor this maybe for a 1.3 release. Lets first make sure that the behavior is correct, is generally usable and doesn't kill your infrastructure. Then I can make it more efficient in the next iteration.

**Comment by far-blue** [comment]
Are those 1000 req/sec fetching data from vault backed by consul? Just curious as I've really not tested the performance of my setup :)

I guess the only problem that might be caused by the frequent renewing of the token is if you have auditing turned on as each renewal will be logged. Maybe for the moment it could just be a configuration option so people can tune it like they can the consul healthcheck.

**Comment by magiconair** [comment]
No, this is a service that is delivering its own cached data. At any rate 30 req/sec don't seem a lot but that doesn't change the validity of your argument. I'll see what I can do to reduce the impact. For now, just increase the refresh time or set it to 0 to disable it.

**Comment by far-blue** [comment]
I've not seen a config option to change the refresh time for vault - does it support the same 'refresh' option as the http cert store?

**Comment by magiconair** [comment]
Well, that's emberrassing :). yes it does. I'll update the docs.

**Comment by far-blue** [comment]
That makes sense and will certainly do for me for now :)

**Comment by far-blue** [comment]
Regardless of the discussion on refresh rates etc. do you feel the improvements for handling vault tokens will be released soon? The fixes will at least allow me to use Vault without needing to supply a root token :)

**Comment by magiconair** [comment]
yes. It's next on the list. Time is a scarce right now. I'll merge it soon.

**Comment by magiconair** [comment]
Merged to master. Lets deal with the fallout in subsequent tickets. @far-blue really appreciate your help and dedication on this one!

**Comment by magiconair** [comment]
Updated the wiki with the new behavior
