### ISSUE TITLE
Is there a channel or forum for asking Fabio questions?

### ISSUE THREAD

**Issue by artburkart** [eBay/fabio#141]
I don't want to spam Issues with small questions that have probably already been asked and answered (but I'm just having no luck finding). If there's a community where questions can be asked, could someone point me there please?

Cheers

**Comment by magiconair** [comment]
So far questions are being asked in the github issues. There is a gitter.im link but there isn't much traffic. I'd like to think that this is because fabio just works but I don't know. Might be time for a mailing list/Google group. In any case feel free to ask your question right here and I'll do my best to respond quickly.

**Comment by artburkart** [comment]
I'll open a ticket that is relevant to my question then! Thanks :)
