### ISSUE TITLE
web sockets and push

### ISSUE THREAD

**Issue by joeblew99** [eBay/fabio#17]
is there any support for http/2 yet ?

Why am i asking ?
HTTP/2 means we no longer have to try to push everything into a few http paylaods anymore.
So, it makes it possible to do web components as micro-services :)
Also i do versioning hashing this way, just to give you an idea:

````

module.exports = {
  baseUrl : 'https://mysite.com/static/',
  resources : {
    vendor : {
      version : 'vendor-d41d8cd98f.js',
      pushWith : [ 'scout' ]
    },
    application : {
      version : 'application-a32e3ec23d.js',
      pushWith : [ 'scout' ]
    },
    secondary : {
      version : 'secondary-e43b8ad12f.js',
      pushWith : [ ]
    }
  }
};

```

**Comment by magiconair** [comment]
HTTP/2 support comes with Go 1.6 and should (TM) work more or less out of the box but I haven't tried that yet. I'm assuming that you want to reduce the number of websocket connections with this or am I missing something?

**Comment by joeblew99** [comment]
OK I guess I have to wait for 1.6.
I was not sure what the integration aspects would be.

Well http/2 allows lots of thinks, and saying adiós to web sockets is one for sure.
But for microservices, it allows me to update all parts of a client in one hit, thus reducing / eliminating the need to manage cross web component update time latencies.

I really like Fabio. Is there a roadmap ?

**Comment by magiconair** [comment]
Thanks. You like anything in particular?

Regarding roadmap: No, not really. I've got some things on my mind which I'll work on but I'm happy to listen to what others would like to see. It won't be everything to everybody but I'm curious what could fit. If you've got an idea please open a ticket. 

If you want to try HTTP/2 you could compile fabio with Go tip and if I understand the HTTP/2 support for 1.6 correctly then that is all you have to do. 

HTTP/2 gives you a more efficient channel between the server and the client so that you don't suffer from TCP slow start and connection management but it doesn't change the routing problem. That's one thing I've really tried to address with fabio: getting rid of the load balancer configuration and provide enough flexibility in the services to allow for fast iterations and simple refactoring. 

So forgive me if I ask again: Where is for you the connection between web sockets, microservices, client upgrades and http/2?

**Comment by magiconair** [comment]
I'm going to close this ticket for now for lack of feedback. Please re-open if you need more information or create specific issues for a feature you want/need to support a concrete use case.
