### ISSUE TITLE
Ridiculous lack for docker documentation

### ISSUE THREAD

**Issue by babatundebusari** [eBay/fabio#175]
I mean i understand fabio comes with docker now but there is ridiculous `LACK` of documentation on usage with docker installation method
 For example take a look at this page https://github.com/eBay/fabio/wiki/Quickstart and tell me where you find anything that has to do with running as docker container

How to run fabio as a docker container and have it work the way it should 
i even tried to find out documentation of setting up `fabio.properties` and couldn't find anything

Also where is documentation on using environment variables to parse to docker container? I haven't seen anywhere on the internet to explains this as well. Documentation is really really lacking as far as running as docker container

**Comment by magiconair** [comment]
Please have a look at https://github.com/eBay/fabio/wiki/Features#docker-support and let me know what is unclear or missing. 

You can find this link in the right menu in the wiki page under Docker Support. 

As a side note I would like to ask you to tone your language down a bit. Docker is not my native environment and so far nobody has complained about the lack of insufficiency of documentation. Asking nicely goes a long way.

**Comment by babatundebusari** [comment]
After days of aggressive learning i finally found out use this fabio of a thing
Man comparing what i know now to what documentation  is on this repo, i can tell you that the tone may seem bad but its really honest truth. I mean i am not directing my frustration on any one or you the author, just an honest feeling of what really is.

Like for example where does it state where one can look at the various parameters when running the services to use fabio? How can one make fabio see routes for services? i mean there are so many things missing.

I know those now after searching and searching and trial and error for days.
Anyways thanks for this great project; really awesome, just the documentation need some more work.

**Comment by magiconair** [comment]
I'm glad you've figured it out and please keep asking questions and make suggestions for improvements but stay constructive. It is OK to ask here! It is more helpful to me to understand *what* frustrated you instead of just reading that you are frustrated.

So far nobody has complained much about the documentation and the project has been around for over a year. The Docker images got pulled 50K+ times. It can't be all bad.

The documentation can always be improved but I don't feel that there is a lot of it missing. It may just not be in the place where you've expected it to be which can be fixed with a link.

The Quickstart is intentionally short since in a lot of situations this is how you want to run fabio and these are the things that most people stumble over. There isn't a whole lot of configuration required since this was the whole point of this project. fabio isn't nginx and it doesn't want to be. 

The first sentence on the https://github.com/eBay/fabio/wiki/Features page says to look at the https://github.com/eBay/fabio/blob/master/fabio.properties file where the config options are all documented. 

So for now I've added a link to the Docker support page, the fabio.properties file and the Features overview to the Quickstart page.

I'm going to close this now. Feel free to re-open or open another issue for another question.

Frank
