### ISSUE TITLE
Question: Clarification of monitoring details

### ISSUE THREAD

**Issue by killcity** [eBay/fabio#193]
What exactly does .count, .min and .max indicate? It'd be great to know number of current conns and req/s. I sifted through the documentation but did not find anything relevant. Is there any plan to show aggregate numbers, per explicit tag?

Cheers

**Comment by magiconair** [comment]
`.count` is the request counter for that target. If you want req/s from that number then you need to take the (non-negative) derivative from `.count`. `.min` and `.max` are the total min and max values for `count` AFAIK. Fabio does not directly keep track of the total number of open connections. You have to sum them up over all targets, e.g. `nonNegativeDerivative(sumSeries(*.fabio.requests.count))` (pls look up the correct syntax since I'm winging this from memory)

Does that answer your question?

**Comment by killcity** [comment]
Thanks Frank. It does. In order for my Datadog graphs to auto add/remove nodes from our aggregate graphs, it will need to be done with tags (since each metric reported through the standard namespace is slightly different). Definitely looking forward to tagging support for Datadog. 

We should be putting Fabio into production soon, in multiple datacenters. Looking at some serious req/s. Mostly all very short lived sessions.

Cheers

**Comment by magiconair** [comment]
Sounds good and I'm looking forward to it. Let me know if you have more questions.
