### ISSUE TITLE
Q: Does Fabio have cluster support?

### ISSUE THREAD

**Issue by TargetFocussed** [eBay/fabio#229]
does it have cluster setup  for HA ?

**Comment by magiconair** [comment]
It doesn't need to. Just run multiple instances and distribute traffic across them. Check the wiki for deployment scenarios. 

Frank Schröder

**Comment by magiconair** [comment]
@TargetFocussed Check this: https://github.com/eBay/fabio/wiki/Deployment

**Comment by leprechau** [comment]
@TargetFocussed we use [anycast](https://en.wikipedia.org/wiki/Anycast)  BGP within our infrastructure to provide scale out and resiliency of our reverse proxy layer.


That's just one way though ... you can do similar with standard Linux hosts using [keepalived](http://www.keepalived.org) or other similar tools.

**Comment by magiconair** [comment]
Going to close this since you seem to create new issues for different questions - which is fine.

**Comment by orikalinski** [comment]
Hey,

Regards the question was asked here.
If i'm not wrong, the solution @magiconair mentioned is working only if you're working with random balancing and not round robin for example which suppose to have a 1 place to persist the order.

Regards @leprechau solution, I'm currently using DigitalOcean services which providing Floating IPs which only available on the public network which I tried to avoid and use private network instead.

Any other solution that I can use here in order to use Round Robin with multiple Fabio instances based on the consul cluster advantages without implementing my own round robin implementation using the KV store?

Thank you
