### ISSUE TITLE
Fabio - setup details

### ISSUE THREAD

**Issue by TargetFocussed** [eBay/fabio#235]
I have a consul cluster (consul-server cluster) running on 3 nodes

192.168.1.1
192.168.1.2
192.168.1.3

I have consul-agent (client) and registrator on a separate node
192.168.1.4

Should I install Fabio docker container on each of the consul-server cluster node ?. 

Or it should be installed on consule-agent node (i.e 192.168.1.4) ??

**Comment by magiconair** [comment]
This depends a lot on what it is that you're trying to do, the scale that you need to handle and the type of environment you are deploying into (cloud, physical machines, ...)

For small applications I'd go with three VMs since this is the minimum you need for consul to work. Install consul, fabio and your app on the same machines and run them. Then you've achieved load balancing and high-availability since you don't have a single point of failure. 

If the CPU load becomes too high check who is generating too much load. My guess is that this will be your app so then you move it to separate nodes. If consul/fabio node is still overloaded move fabio to separate nodes. If that still isn't enough start adding consul agents and have your application and fabio use the agents instead of the servers. But you need some significant load or seriously constrained machines to get there IMO.

Start small and make sure that you can scale. Better than starting big and getting overwhelmed with the complexity.

**Comment by magiconair** [comment]
Going to close this since you seem to create new issues for different questions - which is fine.
