### ISSUE TITLE
Documentation: make build before running ./fabio

### ISSUE THREAD

**Issue by strarsis** [eBay/fabio#24]
fabio binary has to be built first after go get github.com/eBay/fabio using
````
make build
````
It may be useful in documentation.

Thank you and
with best regards

**Comment by magiconair** [comment]
That is not necessary since `go get` will run `go install` which will build a binary for fabio and store it in `$GOPATH/bin` Only, if you want a fully static binary on OSX then you need the `Makefile` since it sets the `-tags netgo` for the linker. On Linux this is the default. You can check that with `ldd fabio` and should get no dependencies. 

Also, `go build` has the same effect. The only thing the Makefile does really is to ensure the git hash is stored in the `main.version` variable.

**Comment by strarsis** [comment]
Thank you for your answer.

Yes, go get will also build the binary.
However, the binary will be in folder ./bin/, so it may be helpful to change the example ("To start fabio run") in documentation from 
````
./fabio
````
to
````
./bin/fabio
````

With best regards

**Comment by magiconair** [comment]
The binary will only be in an unexpected folder if you set your `GOPATH` per project. Also, then `go get` will put the binary into `$GOPATH/bin` whereas the source lives in `$GOPATH/src/github.com/eBay/fabio`. I'm going to close this as `wontfix` since this is the documented behavior of Go apps.
