### ISSUE TITLE
Q: Strip go version from binaries in Download section of Releases

### ISSUE THREAD

**Issue by kostyrev** [eBay/fabio#262]
Is there any requirements that force you to upload binaries to Downloads with go version in names?
it causes the complexity in writing any automation scripts for fabio (chef,puppet,ansible) for it is required to specify not only fabio version but go version as well.
Would it be terribly inconvenient for you not to upload binaries with go version in names?

**Comment by magiconair** [comment]
The reason I started doing this is to provide a build of the same code version but with a different go version if a security update for Go became available. This happened for v1.3.3 and v1.3.5 and I've also provided both v1.3.8 as a go1.7.5 and go1.8 build and for v1.2.1 to provide a go1.6.3 and a go1.7 build. This allows for testing of fabio with a new Go version and fall back to the older version if there are issues.

I could solve this differently, mainly by spinning a new version when I upgrade Go and then add that to the changelog. However, since I merge current changes to master between releases this would mean that I would have to keep changes between versions in a branch or I would have to create release branches or more complex version numbers.

I'm not against changing this but I want to retain the aforementioned abilities since I think they are useful. 

Since the fabio repo is completely self contained you can just build it yourself or just strip off the go version from the file name.

Does that make sense?

**Comment by killcity** [comment]
@kostyrev This can be easily stripped out using regex. All config mgmt tools offer some way of parsing these filenames and extracting whatever you want to remove/variable-lize.

**Comment by kostyrev** [comment]
@killcity yes, I could stip out the name of resulting binary but to do that I have to download it first. And to download it I need to specify go version in url path.

**Comment by killcity** [comment]
Go version is set to a specific ```var``` in my playbooks and I drop that in the filename. Are you blindly wanting to download the latest version without respect to changes in Go versions and the version of Fabio itself?

**Comment by kostyrev** [comment]
yep, for as of now I have to update role with two vars: one for fabio_version and second one for fabio_go_version.
That was the thought. But @magiconair explained above the rationale behind specifying go version in Releases pages.
So I'm closing this issue 'cause not very often I have to update versions in my role.
