### ISSUE TITLE
Session persistence

### ISSUE THREAD

**Issue by strarsis** [eBay/fabio#33]
In nginx Plus, one can use [Session Persistence](https://www.nginx.com/products/session-persistence/) for load balancing.
For some apps, their data/state (session data) is not really separated 
(e.g. PHP Sessions without special backend, legacy apps).
In that case, requests for a session should always go to the same backend (route).

Also when fabio instances are also used as backends (nested upstream), 
Session Draining would be helpful, too, for the same kind of apps.

As session detection can be very different, some kind of go callback offered by fabio 
would allow the admin to tailor it, like passing in a dump of HTTP headers and 
the go callback would return a session ID for fabio to decide.

Thank you and
with best regards

**Comment by magiconair** [comment]
Sticky sessions are a pain in general and I'm not a fan. In general, they show that your application needs refactoring since it wasn't designed to run in an HA setup and you are trying to push this problem into the load balancer instead of solving it in the application. Is this an actual problem you have or a hypothetical? Can you explain your use case a bit better?

Session draining is automatic behavior in fabio. Once a route is removed fabio won't send new requests to that target. Existing connections remain active but do not time out. Again, this is an application problem. You need to have proper timeouts there. Generally, when a service is removed from consul you are shutting it down and handling graceful shutdown there. Fabio cannot know what an acceptable timeout is for each service. If the service is not coming down by itself then something will kill it. In either case the TCP connection is reset and fabio terminates that connection.

**Comment by strarsis** [comment]
Thank you for your answer.

I got some old legacy PHP apps I want to put into containers and behind fabio, too.
And those are not sharing their Session data.
I guess it would make more sense refactoring them so they use a central session storage.

With best regards

**Comment by magiconair** [comment]
If a single instance can handle the load then you can make sure that one and only one instance is running at any given time. Maybe try to acquire a consul or mysql lock during startup and if you can't then shutdown again.

**Comment by strarsis** [comment]
So I close this now because this is an issue with the backend app, not with the HTTP(S/2) frontend 
which shouldn't be used to fix this on a wholly different level.

With best regards

**Comment by maxadamo** [comment]
this is still a problem. The issue is old, but after two years not all the applications are stateless. If you have weblogic or jboss you share a session ID among the cluster. If you don't have a clever application server, and you can't change the code of your application, you need to ask your load-balancer to perform the task. 
If it's not a mobile app, you have plenty of options. Linux LVS is perfectly suitable. 
Otherwise, Nginx, HAProxy are probably your best friends.
