### ISSUE TITLE
Easy way of running fabio server in tests

### ISSUE THREAD

**Issue by vpol** [eBay/fabio#38]
When testing microservices, it would be nice to have an ability to run fabio server and register urls manually.

Is there any easy way doing it?

**Comment by magiconair** [comment]
I can think of two ways:

1. You can start up with a property file and set the `proxy.routes` value with a static route. That will disable the dynamic routing update from consul and use only those routes
2. You can set the routes in consul as manual override and remove them afterwards.

I was actually planning to remove the `proxy.routes` feature since I don't see a use-case for it since the whole point of fabio is to not have such an option. 

The more important question for me is why you would want to do this in the first place? If you have microservices and they register in consul during startup or test then fabio will pick their routes up. Maybe you just need to mask your tests with a consul registration/deregistration wrapper to achieve this since this is how your services would act when run in production.

**Comment by magiconair** [comment]
I'm going to close this question for lack of feedback for now. Please re-open if you need more information or create a ticket with a specific feature request for a concrete use case.

Thx
