### ISSUE TITLE
Direct server return?

### ISSUE THREAD

**Issue by rjes** [eBay/fabio#40]
Hi!
Does fabio support direct server return? If not, is this a feature that will be included later?

**Comment by magiconair** [comment]
No, and I don't have plans for it right now since this wouldn't be a simple addition to the existing proxies. I've used that approach in previous setup but that required iptables configuration. What's your use case?

**Comment by rjes** [comment]
I don't have a specific use case yet, other than deliver a huge amount of content lightning fast.
And I understand if it not the top10 of your features since it requires a very specific environment to operate in. (hosting partners doesn't often like the idea to implement asymmetric routing).

**Comment by magiconair** [comment]
So far our experience has been that fabio does not add much to the latency. It isn't zero copy but if you deploy it to each of your frontend nodes it might just work.

**Comment by rjes** [comment]
Another important use case for using DSR is not to be limited by the load balancer interface speed but be able to push content with the bandwidth of <number of frontend server>*<interface speed>.
Btw, thank you for a good job, fabio seems very nice and i really like the integration with consul.

**Comment by magiconair** [comment]
yeah, but if you deploy fabio onto the content servers directly you also don't have that problem. Then it only depends how you distribute your incoming requests. That may be possible with DNS RR but I haven't done that kind of stuff for a while.

**Comment by magiconair** [comment]
And thanks for the compliments :)

**Comment by magiconair** [comment]
I'm going to close this since I'm not sure at the moment how fabio would implement DSR other than manipulating the kernel routing table with `iptables`. Deploying fabio on the content servers comes close enough with the current architecture. Supporting zero copy proxying support may help but is platform dependent and the following thread makes it at least questionable whether there is sufficient benefit.

https://groups.google.com/d/topic/golang-nuts/Fa6AM71CsEg/discussion

Please feel free to re-open when you have more concrete throughput requirements where fabio is the bottleneck.
