### ISSUE TITLE
Service is registered in Consul but does not show up in fabio

### ISSUE THREAD

**Issue by volkantufekci** [eBay/fabio#7]
Hi,
fabio-example works perfectly but I can't register any other service in fabio. 
I'm using /v1/agent/service/register HTTP API of Consul to register a service with tag "urlprefix-/hede".  Consul says the service is registered but nothing happens at the fabio side.
What else should I check?
fabio v1.0.3, consul 0.5.2

**Comment by magiconair** [comment]
If your service does not provide a green health check, or is in maintenance mode or the node it is running on is in maintenance mode then fabio ignores it.

**Comment by volkantufekci** [comment]
fabio doesn't perform health check, it watches health changes in consul, right? 
fabio-example and my service are both running on the same node, so the node is not in maintenance mode and my service seams to be healthy according to "/v1/health/service/<service>" check of Consul:
```
        "Checks": [
            {
                "Node": "ASDF",
                "CheckID": "serfHealth",
                "Name": "Serf Health Status",
                "Status": "passing",
                "Notes": "",
                "Output": "Agent alive and reachable",
                "ServiceID": "",
                "ServiceName": ""
            }
        ]
```
Is there a debug mode or may i increase log level of fabio?

**Comment by magiconair** [comment]
You are right that fabio only looks for changes in the health check. However, this isn't a health check for your service since the `ServiceID` field is empty. The serfHealth is for the consul agent process AFAIK. 

There are a couple of ways on how to provide the health check. You can either have consul call an HTTP endpoint in your service (e.g. `/health`) which needs to return `200 OK` if it is ok. Or you can call consul yourself and tell it that your service is still alive. Check the [consul documetation](https://consul.io/docs/agent/checks.html) on health checks.

`fabio-example` [lines 76-80](https://github.com/magiconair/fabio-example/blob/master/main.go#L76-L80) register the service health check as an HTTP check (consul will call fabio-example) and [lines 46-49](https://github.com/magiconair/fabio-example/blob/master/main.go#L46-L49) configure the health check handler which just returns OK with status code 200.

I will update the README to make this more clear.

**Comment by volkantufekci** [comment]
I was not passing a health check configuration while registering the service to consul, which was preventing the route for that service to be added by fabio. After I did that fabio added routes perfectly. Thanks for pointing that.

As you mentioned it would be nice to have a line in README that a health check must be defined while registering a service to consul for fabio...

Thanks for implementing fabio.

**Comment by magiconair** [comment]
Done. Thank you :)

https://github.com/eBay/fabio/blob/master/README.md#quickstart

**Comment by jrusiecki** [comment]
Hi,
First of all - it's great !
Yesterday I've bumped into same problem of required check ... fixed it but the question remains: WHY do u need ckeck registered ? 
U can call some API endpoints with ?passing parameter (e.g. /v1/health/service/mywebbackend?passing ) to get proper list of running service instances - both when check is registered & passing AND when consul assumes it is passing because no check is registered for service instance. 
So maybe checks are not required (such behavior looks to me more consul-consistent)
Regards and thanks againfor great fabio LB, Jakub

**Comment by magiconair** [comment]
@jrusiecki thank you. If you don't register a health check then I don't know whether your registered instance is actually alive. All I know is that the consul agent where the app was registered on is alive. This isn't enough to build a routing table.

**Comment by jrusiecki** [comment]
Dear @magiconair thanks for prompt reply. I fully agree with you that fabio shall route locations to live instances only. My suggestion was based solely on the responsibility division- the service discovery service (via endpoint /v1/health/service/mywebbackend?passing and via DNS as well) tells everybody if service instance is alive ("passing"). Thereby, service discovery consumers (e.g. fabio) should dully accept it and not take/care for service discovery (consul) responsibilities. This way we'd have cleaner responsibility separation and less coupling for future consul changes or new service discovery agents. Thanks again and best regards.

**Comment by magiconair** [comment]
@jrusiecki If you do not register your own health check then `/v1/health/service/mywebbackend?passing` will return `200 OK` even if there is no service at all. 

You can try this by registering a service in consul without a health check:

```
curl -XPOST -d '{"ID":"foo1","Name":"foo","Port":1234,"Tags":["urlprefix-/foo"]}' http://localhost:8500/v1/agent/service/register

curl -i 'http://127.0.0.1:8500/v1/health/service/foo?passing'
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 5
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Sat, 22 Oct 2016 07:29:04 GMT
Content-Length: 498

[{"Node":{"Node":"xxx","Address":"127.0.0.1","TaggedAddresses":{"wan":"127.0.0.1"},"CreateIndex":3,"ModifyIndex":5},"Service":{"ID":"foo1","Service":"foo","Tags":["urlprefix-/foo"],"Address":"","Port":1234,"EnableTagOverride":false,"CreateIndex":5,"ModifyIndex":5},"Checks":[{"Node":"xxx","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","CreateIndex":3,"ModifyIndex":3}]}]
``` 

If fabio would not require an actual service health check for `foo` it would try to route traffic to this endpoint.

**Comment by jrusiecki** [comment]
Fully agree. We agree on facts, we just differ on elements responsibility approach.  I think that in this case it's upstream service responsibility to properly register, consul responsibility to properly report service state and any consumer (e.g. fabio) should just list working service instances (passing). 
Less knowledge in fabio how service producer (consul)  works => less code in fabio and it is less dependent on consul internals => less changes to fabio when consul changes and less chances future consul versions break fabio's code...  It is just architectural risk for the future. Regards and thanks for your time and all the explanations.
