### ISSUE TITLE
Recommended way to bind multiple fabio instances to public IP for HA

### ISSUE THREAD

**Issue by nartamonov** [eBay/fabio#89]
Hello! In [Direct deployment](https://github.com/eBay/fabio#direct) scheme it is mentioned that it is possible to have multiple fabio instances for HA and failover. Can you recommend some simple but effective way to bind multiple fabio instances to single public IP? Something like keepalived with MASTER-BACKEND configuration?

**Comment by magiconair** [comment]
We have a netscaler in front of it. On AWS you probably have different options. You can also multiple DNS entries with different ip addresses but the simplest thing is to use a stateless layer 4 switch (ip packet rewriting) with DNAT. Assuming that your L4 switch is also the default gateway all you have to do is to replace the destination address in the incoming packet with one of the fabio instances and dump the packet on the wire again. We used to do that with Linux IPVS but that looks a bit dated now. Not sure if that works with the latest kernel. iptables might do the trick.

Since you only need to shuffle packets around, rewrite them without keeping track you don't need any keepalived magic. The overhead is close to zero.

**Comment by nartamonov** [comment]
@magiconair, thanks! :)

**Comment by joeblew99** [comment]
@nartamonov i have the same HA issue

Did you end up finding a solution with fabio or other to get a pure golang LB that is "clustered" ?
The other option is to use clent side load balancing with consul / DNS

The web clients boot off S3 for wwww.example.com
Within this is a call to a consul proxy to get the server list (prioritised by least load). Its just a list in Javascript. 
The clients then use the top on to make their calls to api.example.com.

If course there are LOTS of issues with this super simle approach:
1- the client can cheat, and DDos a single server.
2. bidirectional stuff like web sockets that are highly latency related need to have a bit more smarts baked in i suspect.

Anyway, i am really needed a HA LB written in golang if anyone has ideas.

**Comment by magiconair** [comment]
@joeblew99 Can you explain what that means: "The web clients boot off S3 for www.example.com" Do they have an internal ip, an external ip, both?
