### ISSUE TITLE
proxy handler error channel bug?

### ISSUE THREAD

**Issue by jhorwit2** [eBay/fabio#92]
My go knowledge isn't super awesome, but I think you are ignoring 1 error in the websocket & raw handler. You can see [here](https://github.com/eBay/fabio/blob/master/proxy/raw.go#L53) how you  spawn 2 goroutines using the cp func, then only wait for 1 error to be returned on the channel. Shouldn't you be waiting for both to return?

**Comment by magiconair** [comment]
In this case it doesn't matter IMO since if either `in` or `out` dies the function returns and closes both `in` and `out` which will terminate the remaining go routine sooner or later. Also, only the first error is interesting since it is the cause and the other one is a consequence of the Reader/Writer being closed. Since the `errc` channel goes out of scope when the function returns and does not escape it should be cleaned up as well including the unconsumed error.

Are you asking out of curiosity or is there an issue you're looking into?

**Comment by jhorwit2** [comment]
Not a known bug i was mainly curious! Thanks!
